# Generated by Django 4.0.3 on 2022-07-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_alter_shoe_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='manufacturer',
            field=models.CharField(default='nike', max_length=50),
            preserve_default=False,
        ),
    ]
